### PR TITLE
add items slider to home page

### PR DESCRIPTION
**Pull request by RobStallion**
Add a category component that allows you to add multiple item components to the slider, which will then be displayed on the homepage.

Also add link to product description (currently Victoria's secret page but will link to Ellie and Andrews code)
#21

### CODE REVIEW

**Comment by eliasmalik** [comment]
27000 lines? maybe add bower_components to the gitignore?

**Comment by RobStallion** [comment]
@eliascodes bower_components are now in .gitignore. Cheers for the spot.

**Comment by franzmoro** [comment]
@RobStallion the bower_components are still in the commit though...

**Comment by otajor** [comment]
Closing this pull request so @RobStallion can push again on a different branch

**Pull request closed without merging**
