### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MyPitit**
I'm updeting the readme, in not finished yet.

### CODE REVIEW

**Comment by franzmoro** [comment]
@MyPitit  this pull request has merge conflicts, can you pull the master version and resolve the issues from your command line / local repo?

**Comment by MyPitit** [comment]
@franzmoro Sure! I'm on it :)

**Comment by MyPitit** [comment]
fixed @franzmoro

**Comment by otajor** [comment]
Cheers, merged :+1:

**Pull request merged**
